# Generated by Django 4.0.5 on 2023-07-23 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='directorgeneral',
            old_name='Laboratorio',
            new_name='laboratorio',
        ),
    ]
